INSERT INTO STUDENT (STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_SECOND_NAME, STUDENT_COURSE) VALUES (100001, 'John', 'Smith', 'DBIT');
INSERT INTO STUDENT (STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_SECOND_NAME, STUDENT_COURSE) VALUES (100010, 'Carl', 'Brown', 'BBIT');

